### ISSUE TITLE
Turn-by-turn navigation on mobile

### ISSUE THREAD

**Issue by alanlaiter** [QwantResearch/qwantmaps#93] opened 2019-08-28 13:18 UTC
When is this functionality rolling out?

**Comment by KAMiKAZOW** [comment] 2019-09-01 09:13
Duplicate of #80. Please close this.

**Closed** 2020-04-10 12:46 UTC

**Comment by Rik44444** [comment] 2022-07-05 10:47
+1 for turn-by-turn navigation for mobile for car, pedestrian and bike !
