### ISSUE TITLE
Add marker for specific location

### ISSUE THREAD

**Issue by seb-jean** [QwantResearch/qwantmaps#53] opened 2019-06-07 08:12 UTC
Hi,

It would be nice to add a marker for specific location because we don't know exactly where location is. For instance for : https://www.qwant.com/maps/#map=12.08/48.8642287/2.3391427

Thanks :)

**Comment by jbgriesner** [comment] 2019-06-10 13:34
Thanks for your relevant suggestion !
This feature will be possible soon ;)

**Comment by seb-jean** [comment] 2019-06-11 07:35
Great!

**Comment by amatissart** [comment] 2019-11-07 15:34
Duplicate of #50, now solved.

**Closed by amatissart** 2019-11-07 15:34 UTC
Labels: enhancement, wip
