### ISSUE TITLE
rendering of the islands show them under water

### ISSUE THREAD

**Issue by zorglubu** [QwantResearch/qwantmaps#69] opened 2019-06-29 18:58 UTC
Islands have the color of the see around :-)
ex : https://www.qwant.com/maps/#map=12.70/46.7158465/-2.3533204

https://www.qwant.com/maps/#map=12.04/46.1864095/-1.2993982

**Comment by amatissart** [comment] 2019-06-30 18:06
Thanks for raising this issue!  
It was caused by a broken polygon representing [the Bay of Biscay / Golfe de Gascogne](https://www.openstreetmap.org/relation/7156290) in OSM data. It should be fixed now (or in a few hours depending on the tiles being cached on your side). 

On a side note, some changes related to this issue were made in OpenMapTiles recently (https://github.com/openmaptiles/openmaptiles/pull/605). So the rendering should be more robust as soon as [the latest release of OpenMapTiles](https://github.com/openmaptiles/openmaptiles/releases/tag/v3.10) is integrated into our tile server deployment.

**Closed** 2019-07-03 14:50 UTC
