### ISSUE TITLE
cannot copy detail from poi popup

### ISSUE THREAD

**Issue by richlv** [QwantResearch/qwantmaps#47] opened 2019-04-15 09:35 UTC
Open details of any POI, for example, https://www.qwant.com/maps/place/osm:node:3733396425@KGB_Building_Corner_House .
Try to select and copy detail from the POI popup, like name, translated name, opening hours and so on - while selecting works, selection is lost while the keyboard shortcut for copying is used.

Reproduced on MacOS with Firefox 66.0.3.

**Comment by jbgriesner** [comment] 2019-04-19 12:51
Thanks for this feedback.
We'll try to reproduce this bug to correct it.

**Comment by amatissart** [comment] 2019-11-07 15:26
It seems to be fixed, I am closing this issue for now.

**Closed by amatissart** 2019-11-07 15:26 UTC
Labels: bug
