### ISSUE TITLE
Display problem on primary highway that not exist in OSM

### ISSUE THREAD

**Issue by plarus** [QwantResearch/qwantmaps#78] opened 2019-07-05 08:22 UTC
There is some display problem on a primary highway in Saint-Ouen-Sur-Seine (France)
No problem on openstreetmap.

OSM: https://www.openstreetmap.org/?mlat=48.91273&mlon=2.33476#map=19/48.91273/2.33476
Qwant: https://www.qwant.com/maps/#map=19.01/48.9126984/2.3348600

Browser : Firefox or Chrome

![QwantMapDisplayPb](https://user-images.githubusercontent.com/16477554/60708569-aa7a2180-9f0e-11e9-982c-461eb5085237.jpg)

**Comment by amatissart** [comment] 2019-07-06 09:37
Thanks for your feedback. 

This is very probably caused by https://github.com/omniscale/imposm3/issues/173  
In a nutshell, ways geometries are sometimes not correctly updated in our database and vector tiles, after one of their nodes has moved in OSM data. 

This bug requires a good understanding of imposm3 internals to be fixed properly, and I hope we'll find the time to dig into it very soon.

**Comment by amatissart** [comment] 2019-11-21 12:29
The fix proposed in https://github.com/omniscale/imposm3/pull/206 is not merged upstream yet.
But Qwant Maps is now using a custom release of imposm that includes this fix. So this issue should no longer exist.

See https://github.com/QwantResearch/kartotherian_docker/pull/83 for more details.

**Closed by amatissart** 2019-11-21 12:29 UTC
